### ISSUE TITLE
[Epic] Profiling visualisation (design doc + features)

### ISSUE THREAD

**Issue by evandandrea** [grafana/phlare#143]
This epic is a catch all for the MVP flamegraph features and design doc containing the investigative takes taken prior to deciding what features we want for the MVP.

- [x] [Design doc](https://docs.google.com/document/d/1AfWs1x5V9G7bZBCWmnbYjH-VMJKR1rLmae68R7GjAkM/edit#heading=h.5sybau7waq2q)
- [x] Base flamegraph visualisation https://github.com/grafana/fire/pull/146
- [x] Flamegraph navigation https://github.com/grafana/fire/pull/149
- [x] Flamegraph search https://github.com/grafana/fire/pull/159
- [x] Flamegraph tooltips
