### ISSUE TITLE
[Epic] Fire Datasource imlementation

### ISSUE THREAD

**Issue by aocenas** [grafana/phlare#147]
Initial implementation of the fire datasource.

- [x] Implement basic querying support https://github.com/grafana/fire/issues/144 https://github.com/grafana/fire/pull/148
- [x] Implement autocomplete for the editor for labels/values https://github.com/grafana/fire/pull/155
- [x] Changing the dataFrame format to remove need for json strings in dataframe https://github.com/grafana/fire/pull/215
- [x] Support query for visual histogram of profile samples
- [x] Table view data
- [ ] Streaming query support
- [ ] Visual query builder [TBD]
- [ ] Profile diff query [TBD]
