### ISSUE TITLE
Add tenant query limits

### ISSUE THREAD

**Issue by cyriltovena** [grafana/phlare#600]
#### Is your feature request related to a problem? Please describe.

We should add overrides and new tenant limits that allow to control how much a tenant can query.

#### Describe the solution you'd like

A new limits for :

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/phlare/issues/740
- [ ] Max time range
- [ ] Max look back period
```

#### Additional context

see https://github.com/grafana/phlare/blob/main/pkg/validation/limits.go
